#!/usr/bin/env python3
"""Canonical method registry — the single source of truth.

Every valuation method is defined ONCE here. `scripts/generate.py` emits the
Python `steps` metadata, TypeScript `lib/methods/*.ts` configs, the calculator
`_NAMED_TOOLS` map, and the MCP `TOOLS` schemas from this file.
"""

RESERVED_WORDS = [
    "function",
    "return",
    "table",
    "field",
    "index",
    "event",
    "select",
    "update",
    "delete",
    "create",
    "if",
    "then",
    "else",
    "end",
    "type",
    "value",
    "none",
    "null",
    "true",
    "false",
    "and",
    "or",
    "not",
    "in",
    "out",
    "set",
    "let",
    "from",
    "where",
    "group",
    "order",
    "limit",
    "start",
    "on",
    "as",
    "return",
]

METHODS = [
    # ── Core ──────────────────────────────────────────────────────────────
    {
        "slug": "scorecard",
        "name": "Scorecard Method",
        "category": "Core",
        "module": "core",
        "function": "scorecard_valuation",
        "formula_number": "3.1",
        "chapter": "Chapter 3: Scorecard Valuation Method",
        "method_name": "scorecard",
        "description": (
            "Adjust average valuation by weighted factor scores for pre-revenue startups. Uses 7 factors "
            "(Team, Product, Market, Competition, Marketing, Funding Need, Other) with standard weights "
            "from the textbook."
        ),
        "transform": "scorecard",
        "inputs": [
            {
                "name": "average_valuation",
                "label": "Average Regional Valuation ($)",
                "type": "number",
                "default": 1500000,
            },
            {
                "name": "w0",
                "label": "Team Score",
                "type": "number",
                "default": 1.25,
                "step": 0.01,
                "description": "Weight: 0.30",
            },
            {
                "name": "w1",
                "label": "Product Score",
                "type": "number",
                "default": 1.5,
                "step": 0.01,
                "description": "Weight: 0.25",
            },
            {
                "name": "w2",
                "label": "Market Score",
                "type": "number",
                "default": 1.2,
                "step": 0.01,
                "description": "Weight: 0.15",
            },
            {
                "name": "w3",
                "label": "Competition Score",
                "type": "number",
                "default": 0.75,
                "step": 0.01,
                "description": "Weight: 0.10",
            },
            {
                "name": "w4",
                "label": "Marketing Score",
                "type": "number",
                "default": 1.0,
                "step": 0.01,
                "description": "Weight: 0.10",
            },
            {
                "name": "w5",
                "label": "Funding Need Score",
                "type": "number",
                "default": 0.9,
                "step": 0.01,
                "description": "Weight: 0.05",
            },
            {
                "name": "w6",
                "label": "Other Score",
                "type": "number",
                "default": 1.0,
                "step": 0.01,
                "description": "Weight: 0.05",
            },
        ],
    },
    {
        "slug": "berkus",
        "name": "Berkus Method",
        "category": "Core",
        "module": "core",
        "function": "berkus_valuation",
        "formula_number": "3.2",
        "chapter": "Chapter 3: Berkus Method",
        "method_name": "berkus",
        "description": (
            "Value a very early-stage (idea to prototype) startup by scoring 5 key risk factors, each worth up to "
            "$500K (max $2.5M)."
        ),
        "inputs": [
            {
                "name": "sound_idea",
                "label": "Sound Idea ($)",
                "type": "number",
                "default": 500000,
                "description": "Max $500K",
            },
            {
                "name": "prototype",
                "label": "Prototype ($)",
                "type": "number",
                "default": 300000,
                "description": "Max $500K",
            },
            {
                "name": "quality_team",
                "label": "Quality Team ($)",
                "type": "number",
                "default": 400000,
                "description": "Max $500K",
            },
            {
                "name": "strategic_relationships",
                "label": "Strategic Relationships ($)",
                "type": "number",
                "default": 250000,
                "description": "Max $500K",
            },
            {
                "name": "product_rollout",
                "label": "Product Rollout ($)",
                "type": "number",
                "default": 200000,
                "description": "Max $500K",
            },
        ],
    },
    {
        "slug": "vc-method",
        "name": "VC Method",
        "category": "Core",
        "module": "core",
        "function": "vc_method_post_money",
        "formula_number": "3.4",
        "chapter": "Chapter 3: Venture Capital Method",
        "method_name": "vc_post_money",
        "description": (
            "Work backward from expected exit value to determine current post-money and pre-money valuation. "
            "Uses target return multiple to discount terminal value."
        ),
        "inputs": [
            {
                "name": "terminal_value",
                "label": "Terminal Value ($)",
                "type": "number",
                "default": 50000000,
                "description": "Expected exit value at time of liquidity event",
            },
            {
                "name": "target_return",
                "label": "Target Return Multiple",
                "type": "number",
                "default": 10,
                "step": 0.5,
                "description": "VC target return (e.g., 10x for early stage)",
            },
        ],
    },
    {
        "slug": "vc-pre-money",
        "name": "VC Method — Pre-Money",
        "category": "Core",
        "module": "core",
        "function": "vc_method_pre_money",
        "formula_number": "3.4",
        "chapter": "Chapter 3: Venture Capital Method",
        "method_name": "vc_pre_money",
        "description": (
            "Determine pre-money valuation by subtracting the investment amount from the post-money valuation."
        ),
        "inputs": [
            {"name": "post_money", "label": "Post-Money Valuation ($)", "type": "number", "default": 5000000},
            {"name": "investment", "label": "Investment ($)", "type": "number", "default": 1000000},
        ],
    },
    {
        "slug": "terminal-value",
        "name": "Terminal Value (Exit Multiple)",
        "category": "Core",
        "module": "core",
        "function": "terminal_value_multiple",
        "formula_number": "3.4",
        "chapter": "Chapter 3: Venture Capital Method",
        "method_name": "terminal_value",
        "description": "Estimate terminal value by multiplying projected revenue by an industry exit multiple.",
        "inputs": [
            {"name": "projected_revenue", "label": "Projected Revenue ($)", "type": "number", "default": 10000000},
            {"name": "multiple", "label": "Exit Multiple (x)", "type": "number", "default": 5, "step": 0.5},
        ],
    },
    # ── SaaS ─────────────────────────────────────────────────────────────
    {
        "slug": "saas-ltv",
        "name": "SaaS LTV (Lifetime Value)",
        "category": "Industry",
        "module": "saas",
        "function": "ltv_saas",
        "formula_number": "11.2",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_ltv",
        "description": (
            "Calculate the Lifetime Value of a SaaS customer based on Average Revenue Per User (ARPU), "
            "gross margin, and monthly churn rate."
        ),
        "inputs": [
            {
                "name": "arpu",
                "label": "ARPU — Average Revenue Per User ($/month)",
                "type": "number",
                "default": 100,
                "description": "Monthly average revenue per user",
            },
            {
                "name": "gross_margin",
                "label": "Gross Margin (%)",
                "type": "number",
                "default": 0.8,
                "step": 0.01,
                "min": 0,
                "max": 1,
                "description": "Gross margin as decimal (0.80 = 80%)",
            },
            {
                "name": "churn_rate",
                "label": "Monthly Churn Rate (%)",
                "type": "number",
                "default": 0.05,
                "step": 0.001,
                "min": 0,
                "max": 1,
                "description": "Monthly customer churn as decimal (0.05 = 5%)",
            },
        ],
    },
    {
        "slug": "saas-cac",
        "name": "SaaS CAC (Customer Acquisition Cost)",
        "category": "Industry",
        "module": "saas",
        "function": "cac",
        "formula_number": "11.2",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_cac",
        "description": "Customer Acquisition Cost = Sales & Marketing Expense ÷ New Customers acquired.",
        "inputs": [
            {
                "name": "sales_marketing_expense",
                "label": "Sales & Marketing Expense ($)",
                "type": "number",
                "default": 500000,
            },
            {"name": "new_customers", "label": "New Customers", "type": "number", "default": 1000, "min": 1},
        ],
    },
    {
        "slug": "saas-nrr",
        "name": "SaaS NRR (Net Revenue Retention)",
        "category": "Industry",
        "module": "saas",
        "function": "net_revenue_retention",
        "formula_number": "11.3",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_nrr",
        "description": "Net Revenue Retention accounts for expansion within the existing customer base.",
        "inputs": [
            {"name": "starting_revenue", "label": "Starting Revenue ($)", "type": "number", "default": 1000000},
            {"name": "ending_revenue", "label": "Ending Revenue ($)", "type": "number", "default": 1100000},
            {"name": "expansion_revenue", "label": "Expansion Revenue ($)", "type": "number", "default": 50000},
        ],
    },
    {
        "slug": "saas-magic-number",
        "name": "SaaS Magic Number",
        "category": "Industry",
        "module": "saas",
        "function": "magic_number",
        "formula_number": "11.4",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_magic_number",
        "description": (
            "Magic Number = Net New ARR ÷ Prior-Quarter Sales & Marketing expense. >0.75 is efficient growth."
        ),
        "inputs": [
            {"name": "net_new_arr", "label": "Net New ARR ($)", "type": "number", "default": 400000},
            {"name": "sm_expense_prior", "label": "Prior-Quarter S&M Expense ($)", "type": "number", "default": 500000},
        ],
    },
    {
        "slug": "saas-rule-of-40",
        "name": "SaaS Rule of 40",
        "category": "Industry",
        "module": "saas",
        "function": "rule_of_40",
        "formula_number": "11.4",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_rule_of_40",
        "description": (
            "Rule of 40 = Revenue Growth Rate + Profit Margin. ≥40% signals healthy balance of growth "
            "and profitability."
        ),
        "inputs": [
            {
                "name": "growth_rate",
                "label": "Revenue Growth Rate (decimal)",
                "type": "number",
                "default": 0.35,
                "step": 0.01,
            },
            {
                "name": "profit_margin",
                "label": "Profit Margin (decimal)",
                "type": "number",
                "default": 0.1,
                "step": 0.01,
            },
        ],
    },
    {
        "slug": "saas-cac-payback",
        "name": "SaaS CAC Payback Period",
        "category": "Industry",
        "module": "saas",
        "function": "cac_payback_period",
        "formula_number": "11.2",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_cac_payback",
        "description": "Months to recover CAC from a customer's monthly gross profit.",
        "inputs": [
            {"name": "cac", "label": "CAC ($)", "type": "number", "default": 1000},
            {"name": "mrr_per_customer", "label": "MRR per Customer ($/month)", "type": "number", "default": 100},
            {
                "name": "gross_margin",
                "label": "Gross Margin (decimal)",
                "type": "number",
                "default": 0.8,
                "step": 0.01,
                "min": 0,
                "max": 1,
            },
        ],
    },
    {
        "slug": "saas-revenue-multiple",
        "name": "SaaS Revenue Multiple Valuation",
        "category": "Industry",
        "module": "saas",
        "function": "saas_revenue_multiple_valuation",
        "formula_number": "11.5",
        "chapter": "Chapter 11: SaaS Valuation Metrics",
        "method_name": "saas_revenue_multiple",
        "description": "Valuation = ARR × Market Revenue Multiple (SaaS typically 5–15x ARR).",
        "inputs": [
            {"name": "arr", "label": "ARR ($)", "type": "number", "default": 5000000},
            {"name": "multiple", "label": "Revenue Multiple (x)", "type": "number", "default": 8, "step": 0.5},
        ],
    },
    # ── Comparables ──────────────────────────────────────────────────────
    {
        "slug": "pe-ratio",
        "name": "P/E Ratio",
        "category": "Foundation",
        "module": "comparables",
        "function": "pe_ratio",
        "formula_number": "5",
        "chapter": "Chapter 5: Market Comparables",
        "method_name": "pe_ratio",
        "description": "Price-to-Earnings ratio: Market Capitalization ÷ Net Income.",
        "inputs": [
            {"name": "market_cap", "label": "Market Capitalization ($)", "type": "number", "default": 500000000},
            {"name": "net_income", "label": "Net Income ($)", "type": "number", "default": 25000000},
        ],
    },
    {
        "slug": "ps-ratio",
        "name": "P/S Ratio",
        "category": "Foundation",
        "module": "comparables",
        "function": "ps_ratio",
        "formula_number": "5",
        "chapter": "Chapter 5: Market Comparables",
        "method_name": "ps_ratio",
        "description": "Price-to-Sales ratio: Market Capitalization ÷ Revenue.",
        "inputs": [
            {"name": "market_cap", "label": "Market Capitalization ($)", "type": "number", "default": 1000000000},
            {"name": "revenue", "label": "Revenue ($)", "type": "number", "default": 100000000},
        ],
    },
    {
        "slug": "ev-ebitda",
        "name": "EV/EBITDA",
        "category": "Foundation",
        "module": "comparables",
        "function": "ev_ebitda",
        "formula_number": "5",
        "chapter": "Chapter 5: Market Comparables",
        "method_name": "ev_ebitda",
        "description": "Enterprise Value ÷ EBITDA — a capital-structure-neutral multiple.",
        "inputs": [
            {"name": "enterprise_value", "label": "Enterprise Value ($)", "type": "number", "default": 500000000},
            {"name": "ebitda", "label": "EBITDA ($)", "type": "number", "default": 50000000},
        ],
    },
    {
        "slug": "ev-revenue",
        "name": "EV/Revenue",
        "category": "Foundation",
        "module": "comparables",
        "function": "ev_revenue",
        "formula_number": "5",
        "chapter": "Chapter 5: Market Comparables",
        "method_name": "ev_revenue",
        "description": "Enterprise Value ÷ Revenue — for growth-stage companies without profits.",
        "inputs": [
            {"name": "enterprise_value", "label": "Enterprise Value ($)", "type": "number", "default": 500000000},
            {"name": "revenue", "label": "Revenue ($)", "type": "number", "default": 100000000},
        ],
    },
    # ── CAPM / TV / Probability ─────────────────────────────────────────
    {
        "slug": "capm",
        "name": "CAPM (Capital Asset Pricing Model)",
        "category": "Foundation",
        "module": "capm",
        "function": "capm",
        "formula_number": "2.5",
        "chapter": "Chapter 2: Valuation Foundations",
        "method_name": "capm",
        "description": "Cost of equity: E(R) = Rf + β × (Market Return − Rf). Returns a decimal rate.",
        "inputs": [
            {
                "name": "risk_free_rate",
                "label": "Risk-Free Rate (decimal)",
                "type": "number",
                "default": 0.04,
                "step": 0.001,
            },
            {"name": "beta", "label": "Beta (β)", "type": "number", "default": 1.5, "step": 0.1},
            {
                "name": "market_return",
                "label": "Market Return (decimal)",
                "type": "number",
                "default": 0.055,
                "step": 0.001,
            },
        ],
    },
    {
        "slug": "startup-capm",
        "name": "Startup-Adjusted CAPM",
        "category": "Foundation",
        "module": "capm",
        "function": "startup_adjusted_capm",
        "formula_number": "2.7",
        "chapter": "Chapter 2: Valuation Foundations",
        "method_name": "startup_capm",
        "description": "Adds size premium and illiquidity premium to the base CAPM for early-stage companies.",
        "inputs": [
            {
                "name": "risk_free_rate",
                "label": "Risk-Free Rate (decimal)",
                "type": "number",
                "default": 0.04,
                "step": 0.001,
            },
            {"name": "beta", "label": "Beta (β)", "type": "number", "default": 1.5, "step": 0.1},
            {
                "name": "market_risk_premium",
                "label": "Market Risk Premium (decimal)",
                "type": "number",
                "default": 0.055,
                "step": 0.001,
            },
            {
                "name": "size_premium",
                "label": "Size Premium (decimal)",
                "type": "number",
                "default": 0.04,
                "step": 0.001,
            },
            {
                "name": "illiquidity_premium",
                "label": "Illiquidity Premium (decimal)",
                "type": "number",
                "default": 0.05,
                "step": 0.001,
            },
        ],
    },
    {
        "slug": "present-value",
        "name": "Present Value",
        "category": "Foundation",
        "module": "tv",
        "function": "present_value",
        "formula_number": "2.2",
        "chapter": "Chapter 2: Valuation Foundations",
        "method_name": "present_value",
        "description": "PV = FV ÷ (1 + r)^n — discount a future cash flow to today.",
        "inputs": [
            {"name": "future_value", "label": "Future Value ($)", "type": "number", "default": 1000000},
            {"name": "rate", "label": "Discount Rate (decimal)", "type": "number", "default": 0.1, "step": 0.01},
            {"name": "periods", "label": "Periods (years)", "type": "number", "default": 5, "min": 0},
        ],
    },
    {
        "slug": "annuity",
        "name": "Annuity Present Value",
        "category": "Foundation",
        "module": "tv",
        "function": "annuity_present_value",
        "formula_number": "2.4",
        "chapter": "Chapter 2: Valuation Foundations",
        "method_name": "annuity",
        "description": "PV of a series of equal periodic payments.",
        "inputs": [
            {"name": "payment", "label": "Periodic Payment ($)", "type": "number", "default": 100000},
            {"name": "rate", "label": "Discount Rate (decimal)", "type": "number", "default": 0.08, "step": 0.01},
            {"name": "periods", "label": "Number of Periods", "type": "number", "default": 10, "min": 1},
        ],
    },
    {
        "slug": "poisson",
        "name": "Poisson Probability",
        "category": "Foundation",
        "module": "probability",
        "function": "poisson_probability",
        "formula_number": "2.5",
        "chapter": "Chapter 2: Valuation Foundations",
        "method_name": "poisson",
        "description": "Probability of exactly k events given a mean rate λ (e.g., k acquisitions per year).",
        "transform": "poisson",
        "inputs": [
            {"name": "rate", "label": "Mean Rate (λ)", "type": "number", "default": 2},
            {"name": "k", "label": "Event Count (k)", "type": "number", "default": 3, "min": 0},
        ],
    },
    # ── Stakeholders ─────────────────────────────────────────────────────
    {
        "slug": "dilution",
        "name": "Single-Round Dilution",
        "category": "Stakeholder",
        "module": "stakeholders",
        "function": "single_round_dilution",
        "formula_number": "13",
        "chapter": "Chapter 13: Stakeholder Valuation",
        "method_name": "dilution",
        "description": "Calculate ownership dilution from a funding round: new ownership = investment ÷ post-money.",
        "inputs": [
            {
                "name": "ownership_before",
                "label": "Ownership Before (decimal)",
                "type": "number",
                "default": 1,
                "step": 0.01,
                "min": 0,
                "max": 1,
            },
            {"name": "investment", "label": "Investment ($)", "type": "number", "default": 1000000},
            {"name": "post_money", "label": "Post-Money Valuation ($)", "type": "number", "default": 5000000},
        ],
    },
    {
        "slug": "common-stock-discount",
        "name": "Common Stock Discount",
        "category": "Stakeholder",
        "module": "stakeholders",
        "function": "common_stock_discount",
        "config_name": "commonDiscountConfig",
        "formula_number": "13",
        "chapter": "Chapter 13: Stakeholder Valuation",
        "method_name": "common_discount",
        "description": (
            "Discount between preferred and common share value (common stock typically 30–80% below preferred)."
        ),
        "inputs": [
            {"name": "preferred_value", "label": "Preferred Value ($)", "type": "number", "default": 10},
            {"name": "common_value", "label": "Common Value ($)", "type": "number", "default": 5},
        ],
    },
    {
        "slug": "opm",
        "name": "OPM Common Stock (Option Pricing Method)",
        "category": "Stakeholder",
        "module": "stakeholders",
        "function": "opm_common_stock",
        "formula_number": "13",
        "chapter": "Chapter 13: Stakeholder Valuation",
        "method_name": "opm",
        "description": (
            "Option-pricing model for common stock valuation — treats common equity as a call option "
            "on enterprise value."
        ),
        "inputs": [
            {"name": "enterprise_value", "label": "Enterprise Value ($)", "type": "number", "default": 30000000},
            {
                "name": "liquidation_preference",
                "label": "Liquidation Preference ($)",
                "type": "number",
                "default": 20000000,
            },
            {"name": "time_to_exit", "label": "Time to Exit (years)", "type": "number", "default": 3},
            {"name": "volatility", "label": "Volatility (decimal)", "type": "number", "default": 0.5, "step": 0.05},
            {
                "name": "risk_free_rate",
                "label": "Risk-Free Rate (decimal)",
                "type": "number",
                "default": 0.04,
                "step": 0.001,
            },
        ],
    },
    {
        "slug": "venture-debt",
        "name": "Venture Debt Dilution",
        "category": "Stakeholder",
        "module": "stakeholders",
        "function": "venture_debt_dilution",
        "formula_number": "13",
        "chapter": "Chapter 13: Stakeholder Valuation",
        "method_name": "venture_debt",
        "description": "Dilution impact of venture debt warrants on equity value.",
        "inputs": [
            {
                "name": "warrant_coverage",
                "label": "Warrant Coverage (decimal)",
                "type": "number",
                "default": 0.08,
                "step": 0.01,
            },
            {"name": "loan_amount", "label": "Loan Amount ($)", "type": "number", "default": 2000000},
            {"name": "post_money", "label": "Post-Money Valuation ($)", "type": "number", "default": 20000000},
        ],
    },
    # ── Marketplace / Emerging ───────────────────────────────────────────
    {
        "slug": "gmv-multiple",
        "name": "GMV Multiple Valuation",
        "category": "Emerging",
        "module": "marketplace",
        "function": "gmv_multiple_valuation",
        "formula_number": "11",
        "chapter": "Chapter 14: Emerging Topics",
        "method_name": "gmv_multiple",
        "description": "Marketplace valuation = GMV × Market GMV Multiple (typically 0.3–0.5x GMV).",
        "inputs": [
            {"name": "gmv", "label": "GMV ($)", "type": "number", "default": 100000000},
            {"name": "multiple", "label": "GMV Multiple (x)", "type": "number", "default": 0.4, "step": 0.05},
        ],
    },
    {
        "slug": "metcalfe",
        "name": "Metcalfe's Law (Network Value)",
        "category": "Emerging",
        "module": "marketplace",
        "function": "network_value",
        "config_name": "networkValueConfig",
        "formula_number": "11",
        "chapter": "Chapter 14: Emerging Topics",
        "method_name": "network_value",
        "description": "Network value = k × n^α. Theoretical α=2; empirical platforms use α≈1.2–1.5.",
        "inputs": [
            {"name": "active_users", "label": "Active Users (n)", "type": "number", "default": 1000000},
            {"name": "k", "label": "Value per Connection (k)", "type": "number", "default": 0.0000001},
            {"name": "alpha", "label": "Exponent (α)", "type": "number", "default": 1.5, "step": 0.1},
        ],
    },
]
